# This is a basic workflow to help you get started with Actions

name: build + scp

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Set gitbook
        run: npm install gitbook-cli -g

      - name: pwd
        run: pwd && ls

#      - name: gitbook install plugins
#        run: gitbook install
#
#      - name: gitbook build
#        run: gitbook build

      - name: result
        run: cd notebook && ls -la
