# This is a basic workflow to help you get started with Actions

name: build + scp

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build Gitbook
    runs-on: ubuntu-18.04
    steps:
      # Check out the repo first
      - name: Checkout code
        uses: actions/checkout@v2

      # install Node
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          version: 14.x

      # install gitbook-cli
      - name: install gitbook-cli
        run: npm install gitbook-cli -g

      # install gitbook-cli
      - name: install && build
        run: gitbook install

      - name: result
        run: ls -la
