# This is a basic workflow to help you get started with Actions

name: build + scp

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build vuepress
    runs-on: ubuntu-20.04
    steps:
      # check repo
      - name: Checkout code
        uses: actions/checkout@v2

      # install node
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 12.x

      # install gitbook-cli
      - name: install yarn
        run: npm install yarn -g

      # install && build
      - name: build
        run: yarn && yarn build

      - name: result
        run: tree docs -a

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: root
          password: ${{ secrets.PASSWD }}
          port: 22
          source: "docs/.vuepress/dist/"
          target: "/root/web/note.zhio.cc/"
